### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by ricardok1** [dotnet/dotnet-monitor#1138]
## Background and Motivation
It's welcome to be fully standalone on-premises 

## Proposed Feature
Exclude all dependencies or be just side binaries 

## Usage Examples
Be able to run in any server architecture

**Comment by jander-msft** [comment]
Could you please describe what you are proposing more specifically? The few statements you have made leave a lot of room for interpretation.

For example, "fully standalone" in my mind means you are asking for a self-contained version rather than a framework-dependent version.

Not sure what you mean by "on-premise" since dotnet-monitor is installable via the "dotnet tool" command AND is available as a pre-built container image.

Please clarify "exclude all dependencies or just be side binaries".

As for server architectures, the tool has no specific dependence on any architecture. If you see it failing on a specific architecture, please file an issue with specific information about the usage of the tool and its environment.

**Comment by ricardok1** [comment]
Just add to the project as library without any dependecy - as far of the introduction it depends in sdk to run

**Comment by jander-msft** [comment]
> Just add to the project as library without any dependecy - as far of the introduction it depends in sdk to run

Again, you'll have to better describe what you'd like supported because "dotnet-monitor as a library" can take several forms:
1. If you want to just be able to execute the underlying pipelines to get the artifacts from your code, those already exist in the https://github.com/dotnet/diagnostics repo.
1. If you also want the HTTP layer hosted from your library/process, that'll take bit of work for us to support, but that also has two primary variations: is the HTTP layer only reporting diagnostics for the hosting process (to allow self-diagnosis) or do you want to diagnose multiple other processes, just like dotnet-monitor.
1. Or maybe you have some other goal in mind that I haven't thought of.

**Comment by SanderSade** [comment]
I believe OP wanted a NuGet package or somesuch that can be used run in non-container production servers. E.g. Azure App Service, barebone IIS or Windows Server, Azure Service Fabric and so forth. 

Right now Monitor seems to be limited to local commandline or Docker image, which is rather odd, considering by far most of the .NET does not run that way.

**Comment by jander-msft** [comment]
Please reopen if you'd like to further discuss your request.
