### ISSUE TITLE
Getting started on setting up locally

### ISSUE THREAD

**Issue by martinmine** [dotnet/dotnet-monitor#1140]
### Documentation Request

The "getting started" on the documentations page does not link anywhere: https://github.com/dotnet/dotnet-monitor/tree/main/documentation# 
It would be super helpful for new users of this tool on a simple and clear set of steps on how to set this up which clarifies:
- Which endpoints are available on HTTP/HTTPS, I was expecting that the app listened on the same endpoints on HTTP and HTTPS but this [did not seem to be the case](https://github.com/dotnet/dotnet-monitor/issues/1139).
- Which endpoints require authentication, and how to obtain an auth token
- Would also be nice with documentation on how to trust the self-signed cert with the app

**Comment by jander-msft** [comment]
The entire HTTP API is documented at https://github.com/dotnet/dotnet-monitor/blob/main/documentation/api/README.md, where each route describes whether it is authenticated and what its default host address is (including  HTTPS vs HTTP). Each authenticated endpoint links to the authentication documentation and how to generate the key.

The certificate is specified via configuring the default certificate via the Kestrel:Certificates:Default key: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#replace-the-default-certificate-from-configuration

**Comment by surfmuggle** [comment]
If the [getting started guide](https://github.com/dotnet/dotnet-monitor/tree/main/documentation/gettingStarted/) would contain a tutorial how to install, run and configure dotnet-monitor with a given example this would be helpfull. 

What steps are needed to use dotnet-monitor on my local machine?

I would assume and hope for a list like this

1. build [dotnet-monitor](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/building.md) locally
2. copy the exe / assembly.dll from the build to ...
3. in your website configure in the pipleine to integrate ...
4. to see the result open ...

It seems that [introducing dotnet-monitor](https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/) is something that we are loolking for

1. You can install dotnet-monitor as a global tool using the following command:  `dotnet tool install -g dotnet-monitor --add-source https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet-tools/nuget/v3/index.json --version 5.0.0-preview.*`
2.  run dotnet-monitor via the following command: `dotnet monitor collect`

So i assume that dotnet-monitor captures all process that running in the dotnet-runtime process?

- Does it "grab" the communication from inside "dotnet.exe" or "dllhost.exe"? 
- What if i have multiple websites running but only want to grab the process of a certain website / webservice? 
- Can i use the Process ID to capture only certain processes?

Based on [introducing dotnet-monitor](https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/)  i assume that to get the results for a certain process i would for example call the endpoint `GET /process?pid={pid}&uid={uid}&name={name} HTTP/1.1`. 

 - What is the reommended Origin for this get-request. Would you recommend to use somehting like CURL or do i fire up another dotnet-web app to query the api?
 - Based on the [sample request to the api metrics](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/api/metrics.md#sample-request) i assume that i have to set up a [filter](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#filters) to query a certain website. If the getting-started-guide would be a tutorial with an exmple this would help immensly to get it running easier. 

Thanks and regards

**Comment by wiktork** [comment]
> Does it "grab" the communication from inside "dotnet.exe" or "dllhost.exe"?

Dotnet applications expose a diagnostics endpoint that we rely on for getting diagnostic data:
https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#:~:text=Diagnostic%20IPC%20Protocol%201%20General%20Flow.%20All%20communication,...%207%20Process%20Commands.%20...%208%20Errors.%20

> What if i have multiple websites running but only want to grab the process of a certain website / webservice?

As you pointed out you can use pid, runtime id, or name to point to a specific process. [Default Process config](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#default-process-configuration) can be used to set a default as well.

> What is the reommended Origin for this get-request. Would you recommend to use somehting like CURL or do i fire up another dotnet-web app to query the api?

We do not require a specific origin. Curl is a good choice because it allows streaming data from text based endpoints such as /logs, but it depends on how you want to use it. 

For metrics, we respect the default process filter as well. Note the other filter link is for collection rules. Checkout https://devblogs.microsoft.com/dotnet/announcing-dotnet-monitor-in-net-6/ and https://github.com/dotnet/dotnet-monitor/blob/main/documentation/collectionrules.md

**Comment by mac2000** [comment]
Also trying to figure out how to get up and running (end goal is to have Prometheus compatible `/metrics`)

After bazillion of attempts to get it running in Kubernetes, I give up and decided to give it a try on a local Windows machine, but the behavior is same

So I'm running a simple API (dotnet 6.0)

Then from the task manager I got its PID, also checked that I have pipe:

```bash
get-childitem \\.\pipe\ | grep dotnet
```

Successfully starting globally installed dotnet monitor:

```bash
dotnet monitor collect --no-auth --temp-apikey -m --diagnostic-port \\.\pipe\dotnet-diagnostic-43748
```

But when I try to open the desired link, I got an empty response and in monitor logs, there is only:

```
16:54:01 info: Microsoft.Diagnostics.Monitoring.WebApi.OutputStreamResult[5]
      => SpanId:73515143d91d5d4c, TraceId:7d354f59ed4a2cfbceb140e5524e8a04, ParentId:0000000000000000 => ConnectionId:0HMDHMKBP8SU3 => RequestPath:/metrics RequestId:0HMDHMKBP8SU3:00000002 => Microsoft.Diagnostics.Monitoring.WebApi.Controllers.MetricsController.GetMetrics (Microsoft.Diagnostics.Monitoring.WebApi) => ArtifactType:metrics
      Written to HTTP stream.
```

Did tried to open logs endpoint (not really needed but just in case) and receiving 

```json
{
"status": 400,
"detail": "No default process configuration has been set."
}
```

And in logs:

```
16:55:12 fail: Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController[1]
      => SpanId:6b8646d4b310e305, TraceId:e3096a71df3a005320ad07524944265a, ParentId:0000000000000000 => ConnectionId:0HMDHMKBP8SU3 => RequestPath:/logs RequestId:0HMDHMKBP8SU3:00000003 => Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureLogs (Microsoft.Diagnostics.Monitoring.WebApi) => ArtifactType:logs
      Request failed.
      System.InvalidOperationException: No default process configuration has been set.
         at Microsoft.Diagnostics.Monitoring.WebApi.DiagnosticServices.GetProcessAsync(DiagProcessFilter processFilterConfig, CancellationToken token) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs:line 100
         at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.<>c__DisplayClass32_0`1.<<InvokeForProcess>b__0>d.MoveNext() in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs:line 687
      --- End of stack trace from previous location ---
         at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagControllerExtensions.InvokeService[T](ControllerBase controller, Func`1 serviceCall, ILogger logger) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagControllerExtensions.cs:line 57
```

Without being able to run it locally there is no chance I can run it anywhere 🤷‍♂️

And indeed there is a lack of documented examples of how to get everything up and running, hopefully, see it in the future, the project is really promising and hopefully will be a game-changer 💪

**Comment by jander-msft** [comment]
> Then from the task manager I got its PID, also checked that I have pipe:
> 
> ```shell
> get-childitem \\.\pipe\ | grep dotnet
> ```
> 
> Successfully starting globally installed dotnet monitor:
> 
> ```shell
> dotnet monitor collect --no-auth --temp-apikey -m --diagnostic-port \\.\pipe\dotnet-diagnostic-43748
> ```

You should not be specifying `--diangostic-port` with the name of an existing named pipe or Unix domain socket. The `--diagnostic-port` option is used for telling `dotnet monitor` to establish a listening server at the specified location (which then requires you to set the DOTNET_DiagnosticPorts environment variable on the target processes with the same name you specified for this option so that the target process can reach out to `dotnet monitor` to establish the diagnostics connection). This is our recommended setup for multi-container environments or if you want to have `dotnet monitor` only observe a select set of processes.

If you start `dotnet monitor` using `dotnet monitor collect --no-auth`, then you can do a GET on `https://localhost:52323/logs?pid=43748` to get logs from the process with ID 43748. If you want to use the endpoints without specifying the process ID/name/etc, you'll have to [configure the default process](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#default-process-configuration).

**Comment by jander-msft** [comment]
The documentation now has information on how to run [locally](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/localmachine.md), in [Docker](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/docker.md), and in [Kubernetes](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md).
