### ISSUE TITLE
Support for Windows containers

### ISSUE THREAD

**Issue by fschmied** [dotnet/dotnet-monitor#1160]
Is it supported to use the `dotnet monitor` sidecar container approach with Windows containers, i.e., on a Windows Kubernetes node? If so, how would one map the diagnostic data named pipes between the two containers?

Or would this setup require running `dotnet monitor` within the same container as the application as a workaround?

**Comment by jander-msft** [comment]
At this time, it is likely not possible to run `dotnet monitor` as a Windows sidecar container to diagnose applications in another Windows container. This is largely due to the fact that the diagnostic pipe's implementation is a named pipe. It's my understanding that named pipes cannot be shared among Windows containers but can only be provided via a host mount: https://docs.docker.com/storage/#:~:text=named%20pipes%3A%20An%20npipe%20mount%20can%20be%20used,the%20Docker%20Engine%20API%20using%20a%20named%20pipe. One possible way to alleviate this in the future is https://github.com/dotnet/runtime/issues/63950

For now, you will have to run `dotnet monitor` within the same container as the application.
