### ISSUE TITLE
container-to-container dump retrieval

### ISSUE THREAD

**Issue by josalem** [dotnet/dotnet-monitor#12]
dotnet-monitor always requests that memory dumps be written to `$TMPDIR`.  In the .net5.0 container-to-container configuration, `$TMPDIR` is not guaranteed to be the shared file mount.  In that case, dotnet-monitor needs a solution for specifying where the dump should be created (from the target application's perspective).  The location of the dump is sent via the Diagnostic Port to the target process.  The requested dump location is resolved by the target application.  If the shared file mount is not at the same path in both the target container and the dotnet-monitor container, then dotnet-monitor won't be able to access the dump.  dotnet-monitor needs to be made aware of the relative path difference of the shared file mount between the two containers.  This becomes complex if there are more than 2 containers in a Pod and each container has mounted the shared file mount to a different path.

CC @wiktork @noahfalk @jander-msft @shirhatti

**Comment by jander-msft** [comment]
At this time, allowing the definition of where the shared dump location exists between target application containers vs the .NET Monitor container will not be added. The current expectation, at is has been since the beginning of the tool offering, is that the volume is mounted at the same location in all involved containers.
