### ISSUE TITLE
Any reason for the special dependence injection

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#1240]
Hi, a little curious about the dependency injection usage in the controller

https://github.com/dotnet/dotnet-monitor/blob/0eed70ab1e9d11b09cc09d036116cfa0f8ffd7a5/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/MetricsController.cs#L27-L35

https://github.com/dotnet/dotnet-monitor/blob/0eed70ab1e9d11b09cc09d036116cfa0f8ffd7a5/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs#L29-L33

Why do we inject related services directly, maybe there're some reasons this way is better?

**Comment by jander-msft** [comment]
These might be artifacts of from when dotnet-monitor originally was built from the dotnet/diagnostics repo or some inability of DI to see these services due to access modifiers on the implementations. These could possibly be changed to using injection.

**Comment by WeihanLi** [comment]
Thanks @jander-msft

**Comment by jander-msft** [comment]
Looking into this further, the reason why some of classes are using `IServiceProvider` rather than direct injection is due to visibility scopes. The constructors of these classes are public (and the classes themselves are public) but some of the service types they are acquiring are internal, so they cannot be parameters to the public constructor. This, the `IServiceProvider` is injected and the services can be acquired within the constructor.

**Comment by WeihanLi** [comment]
Found that just now 😄 
![image](https://user-images.githubusercontent.com/7604648/148163952-4f070788-2528-4696-bf82-349f6cdb86fc.png)
