### ISSUE TITLE
Question: the `Listen` `ConnectionMode` is only for .NET 5 +?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#1274]
Seemed the `Listen` mode is only available for .NET 5 +?

When I try to use `Listen` mode with a .NET Core 3.1 App, no processes could be found and no metrics would be outputted, while when I switch to `Connect` mode, it works fine.

**Comment by WeihanLi** [comment]
Are there some more details about the `ConnectionMode`, which mode is better for the Kubernetes container environment?

Currently the Kubernetes sample is using `Listen` mode

**Comment by jander-msft** [comment]
`dotnet monitor`s 'listen' mode is only supported for .NET 5+ target processes. In this mode, `dotnet monitor` establishes a diagnostic server at the specified path and waits for target processes to connect to it.

You can read more about connect vs listen mode for the target processes at https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#diagnostic-ports

Note that whichever mode the target processes are in, you want `dotnet monitor` to be in the opposite mode (e.g. target processes 'listen' while `dotnet monitor` connects; target processes 'connect' while `dotnet monitor` listens).

In Kubernetes, we recommend to configure `dotnet monitor` to be in 'listen' mode for a number of reasons.
1) If target processes are only configured for 'listen' mode, you have to mount `/tmp` between all of the target containers and the `dotnet monitor` container. All of the target processes likely have a process ID of `1`. The diagnostic tools use the process ID to distinguish processes when trying to connect to them, so there would be ambiguity as to which process you really want and `dotnet monitor` will likely only see all of the target processes as a single process if they have the same process ID. This issue does not occur when the diagnostic tools are configured to be in 'listen' mode and the target processes 'connect' to the tools.
1) The collection rules feature of `dotnet monitor` only works when it is configured to 'listen' for target processes.
1) Because target processes have their runtime suspended (by default) when in 'connect' mode, diagnostic tools can do some interesting things such as capture traces from the very beginning of running the managed code in the process. For example, assembly loads and bindings can be captured using the collection rule feature in `dotnet monitor`.

**Comment by WeihanLi** [comment]
Got it, great thanks for your reply @jander-msft
