### ISSUE TITLE
How to run dotnet monitor as a local development tool on Windows

### ISSUE THREAD

**Issue by AvtsVivek** [dotnet/dotnet-monitor#1551]
### Documentation Request

Just came across this [**on dotnet video**](https://www.youtube.com/watch?v=oCY9BsAw5oU) about [dotnet-monitor](https://github.com/dotnet/dotnet-monitor) and wanted to try out [on my local machine](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/localmachine.md) without getting into container complications. 

### Previous documentation

I looked [at this page and installed the tool globally on my machine](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/setup.md#setup). 

![image](https://user-images.githubusercontent.com/41255281/156384435-0a283374-8e45-4d30-9b6d-44ea1b811756.png)

I then created a starter web app and got it running in Visual Studio.

![image](https://user-images.githubusercontent.com/41255281/156385888-2fc9be5b-6261-47b0-ae03-b733a04b08bf.png)

Now what should I do to monitor this simple app.

The [documentation here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/localmachine.md#local-configuration) is not clear enough. What would be the **ProcessName**, the key and the value **BuggyDemoWeb** be in my case?

```json
{
    "$schema": "https://aka.ms/dotnet-monitor-schema",
    "DefaultProcess": {
        "Filters": [{
            "Key": "ProcessName",
            "Value": "BuggyDemoWeb"
        }]
    }
}
```

Is there any documentation around that I am missing? 
For me, if there are not step by step tuts, its good for nothing. 

For example [Dapr](https://dapr.io/) has a good set of [documentation](https://docs.dapr.io/getting-started/) as well as [tutorials](https://github.com/dapr/dotnet-sdk/tree/master/examples) and [samples](https://github.com/dapr/dotnet-sdk/tree/master/samples/Client)

**Comment by jander-msft** [comment]
> What would be the **ProcessName**, the key and the value **BuggyDemoWeb** be in my case?

It's the name of the process for which you want to enable the default process routes. We cannot tell you what that value is. From your screen shot, it could be `StarterWebApp`, it could be `dotnet` (which is not a good process name filter for local scenarios since you could easily have more than one process named `dotnet`), or something else if you configured it to be different. You'll have to run your application, get its process name, and put it in this field.

In any event, the default process filter is not strictly required to use dotnet monitor. The non-default process routes still work; they are the same routes but you have to use a query parameter to specify for which process you want information.
