### ISSUE TITLE
dotnet monitor memory usage keep increasing gradually

### ISSUE THREAD

**Issue by LaurenceChau** [dotnet/dotnet-monitor#2646]
##

### Description

when dotnet-monitor running as a windows process, it keep consuming the memory gently and the memory used by dotnet-monitor can be added up to over 1GB. The memory usage will only go up gradually and I haven't seen the memory usage go down again.

### Configuration

dotnet-monitor version
```
6.2.2+8abeb94c15ee4175d7078a3f768ed1ef15032bd8
```

dotnet-monitor config
```
Tell us about your experience with dotnet monitor: https://aka.ms/dotnet-monitor-survey

{
  "urls": "https://localhost:52323",
  "Kestrel": ":NOT PRESENT:",
  "Templates": ":NOT PRESENT:",
  "CollectionRuleDefaults": ":NOT PRESENT:",
  "GlobalCounter": {
    "IntervalSeconds": "5"
  },
  "CollectionRules": ":NOT PRESENT:",
  "CorsConfiguration": ":NOT PRESENT:",
  "DiagnosticPort": {
    "ConnectionMode": "Connect",
    "EndpointName": null
  },
  "Metrics": {
    "Enabled": "True",
    "Endpoints": "http://localhost:52325",
    "IncludeDefaultProviders": "True",
    "MetricCount": "3"
  },
  "Storage": {
    "DumpTempFolder": "C:\\Users\\laurence\\Temp"
  },
  "DefaultProcess": {
    "Filters": [
      {
        "ProcessName": "NetworkMonitor"
      }
    ]
  },
  "Logging": {
    "Console": {
      "FormatterName": "simple",
      "FormatterOptions": {
        "IncludeScopes": "True",
        "TimestampFormat": "HH:mm:ss "
      }
    },
    "EventLog": {
      "LogLevel": {
        "Default": "None",
        "Microsoft": "None",
        "Microsoft.Diagnostics": "None",
        "Microsoft.Hosting.Lifetime": "None"
      }
    },
    "LogLevel": {
      "Default": "None",
      "Microsoft": "None",
      "Microsoft.Diagnostics": "None",
      "Microsoft.Hosting.Lifetime": "None"
    }
  },
  "Authentication": ":NOT PRESENT:",
  "Egress": ":NOT PRESENT:"
}
```

I am not sure if it is a bug or not. However, this document suggested that the dotnet-monitor only consume minimal cpu and memory resource. 
https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md#recommended-container-limits

Do you have any fine-tuning guild to restrict the Dotnet-monitor memory usage?

### Other information
![image](https://user-images.githubusercontent.com/13799490/194895704-efd87029-b70c-40ea-98fb-f78b2cbbe52b.png)

**Comment by jander-msft** [comment]
ASP.NET Core applications (which is what dotnet-monitor is) run in GC Server mode (https://learn.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-6.0#workstation-gc-vs-server-gc) by default but will fallback to workstation mode if only one logical CPU core is available. Since you are running it on your local machine and it likely has more than one CPU core, then it is probably running in Server mode.

Because it is running in Server mode, it will continue to collect memory as needed and GCs occur less frequently. If pressured by the OS, it will free up the unused memory. In Workstation mode, GCs are more frequent but will keep the used memory lower at the cost of using more CPU and more frequent (albeit short) pauses in application execution.

You can force the GC to be in Workstation mode by setting the `DOTNET_gcServer` environment variable to `0` to see if this has the desired memory characteristics that you are looking for: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#workstation-vs-server

**Comment by LaurenceChau** [comment]
Cool. After adding the environment variable `DOTNET_gcServer=0`  to dotnet-monitor, the memory consumption remain at ~ 50MB without further increase. Thanks a lot. TIL.
