### ISSUE TITLE
Why shareProcessNamespace: true is not required when we run dotnet-monitor as a sidecar?

### ISSUE THREAD

**Issue by neilzzy** [dotnet/dotnet-monitor#380]
While running dotnet cli tools, such as dotnet-dump, in a sidecar, we need to have shareProcessNamespace: true in the yml file.

**Comment by jander-msft** [comment]
The diagnostic tools typically discover processes using 'connect' mode (they scan a specific pipe/socket name format for diagnosable processes). This mode requires that the target applications that are publishing their diagnostic pipe/socket exist in the same process namespace as the diagnostic tool. In a multi-container Linux environment, this also requires that the `/tmp` folder is shared among the application containers and the diagnostic tool container (so that the diagnostic tool can access the diagnostic socket). This is also true for the `dotnet monitor` diagnostic tool when running in 'connect' mode, which is its default mode. This mode works well when you run the diagnostic tool in the same process namespace as the target applications (e.g. in the same container or on your local machine).

However, if `dotnet monitor` is set up to run in 'listen' mode (by specifying the `--diagnostic-port` command line argument or through [configuration](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#connection-mode)), sharing the process namespace is not necessary because the target processes are connecting to the `dotnet monitor` tool through the diagnostic port. There's also no need to share the `/tmp` directory for the same reason. Because the diagnostic port is bound to a location in each container that you've configured, you are able to specifically tell each of the application targets to connect to that diagnostic port without having to use the discovery mechanism that is limited to using the `/tmp` directory.

When wanting to diagnose applications in a multi-container environment, it is our recommendation that `dotnet monitor` is used and that it is configured to run in `listen` mode to avoid having to disable portions of the container isolation.

**Comment by neilzzy** [comment]
> The diagnostic tools typically discover processes using 'connect' mode (they scan a specific pipe/socket name format for diagnosable processes). This mode requires that the target applications that are publishing their diagnostic pipe/socket exist in the same process namespace as the diagnostic tool. In a multi-container Linux environment, this also requires that the `/tmp` folder is shared among the application containers and the diagnostic tool container (so that the diagnostic tool can access the diagnostic socket). This is also true for the `dotnet monitor` diagnostic tool when running in 'connect' mode, which is its default mode. This mode works well when you run the diagnostic tool in the same process namespace as the target applications (e.g. in the same container or on your local machine).
> 
> However, if `dotnet monitor` is set up to run in 'listen' mode (by specifying the `--diagnostic-port` command line argument or through [configuration](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#connection-mode)), sharing the process namespace is not necessary because the target processes are connecting to the `dotnet monitor` tool through the diagnostic port. There's also no need to share the `/tmp` directory for the same reason. Because the diagnostic port is bound to a location in each container that you've configured, you are able to specifically tell each of the application targets to connect to that diagnostic port without having to use the discovery mechanism that is limited to using the `/tmp` directory.
> 
> When wanting to diagnose applications in a multi-container environment, it is our recommendation that `dotnet monitor` is used and that it is configured to run in `listen` mode to avoid having to disable portions of the container isolation.

Thanks for detailed sharing.
Regarding /tmp directory, it seems dotnet-monitor can no longer find any other processes if I comment out tmp volume mount for it.
![image](https://user-images.githubusercontent.com/32922864/121804346-73732580-cc78-11eb-91f1-7a924ca47106.png)
...
      shareProcessNamespace: true
      volumes:
      - name: diagnostics
        emptyDir: {}
      containers:
      - name: server
        image: myacr.azurecr.io/diagapp:1658
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /tmp
            name: diagnostics
      - name: sidecar
        image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.1
        ports:
        - containerPort: 52325
        #args: ["--urls", "http://*:52323", "--metricUrls", "http://*:52325"]
        **#volumeMounts:
          #- name: diagnostics
            #mountPath: /tmp**
.....

Am I missing anything? 
Is monitor:5.0.0-preview.1 not running in 'listen' mode? If so, why shareProcessNamespace is not necessary as you shared?
