### ISSUE TITLE
Use queries instead of path segments

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#66]
e.g. /logs?pid=1
/dump?uid={guid}

**Comment by jander-msft** [comment]
I'm trying to remember where we landed for the /processes routes. Would it be:

| Route | Description |
| --- | --- |
| `/processes` | Enumerates all processes |
| `/process?pid=1` | Gets process with ID = 1 |
| `/process?uid={guid}` | Gets process with unique ID = {guid} |
| `/env?pid=1` | Gets environment of process with ID = 1 |
| `/env?uid={uid}` | Gets environment of process with unique ID = {guid} |

How would a user be able to identify the default process since we're now codifying that notion in configuration?

**Comment by wiktork** [comment]
> How would a user be able to identify the default process since we're now codifying that notion in configuration?
IIRC this was an outstanding issue. For 202 (i.e. egress) calls, this could be returned as part of the response, but it would not work for direct download operations.

I think your table makes sense (we had discussed adding /env). Perhaps the default process information can we requested "naturally"?
/process?pid=1 <info about pid 1>
/process <info about the default process, or error if not configured>
/env <env for default process>

**Comment by jander-msft** [comment]
> > How would a user be able to identify the default process since we're now codifying that notion in configuration?
> 
> IIRC this was an outstanding issue. For 202 (i.e. egress) calls, this could be returned as part of the response, but it would not work for direct download operations.
> 
> I think your table makes sense (we had discussed adding /env). Perhaps the default process information can we requested "naturally"?
> `/process?pid=1 <info about pid 1>`
> `/process <info about the default process, or error if not configured>`
> `/env <env for default process>`

I think that makes sense. I think we should also add some additional data on each item for the `/processes` route to (1) identify which is the default process e.g. `"isDefault": [true|false]`.

**Comment by kkeirstead** [comment]
What should we do if a user attempts to provide, for example, a PID and a UID (or any combination of PID, UID, and name)? Should we choose to default to one of the values, or should we automatically throw out any request that specifies multiple identifiers? In theory, if provided with multiple identifiers that are all associated with the same process, the information is just redundant. On the other hand, if a PID for one process is provided alongside a UID for a different process, I think we need to establish a precedent for how we handle those cases.

**Comment by jander-msft** [comment]
I think if a user providers multiple identifiers, then all of those identifiers must be matched. Thus, if `pid=5&name=WebApp1`, then we'll try to find a single process that has (1) a process ID of 5 AND (2) a process name of WebApp1. Use the existing behavior for when no process is found or when multiple processes are found.

For the names of the query parameters, I think they should be:
| Parameter Name | Description |
|---|---|
| pid | the process ID |
| uid | the runtime instance cookie |
| name | the name of the process |
| entrypoint | the name of the entrypoint assembly |

Don't worry about entrypoint yet since that is still being plumbed into the NETCore.Client library.

@dotnet/dotnet-monitor, what do you think?

**Comment by wiktork** [comment]
> I think if a user providers multiple identifiers, then all of those identifiers must be matched.

+1, it will make it easy to incorporate into the existing DiagProcessFilter infrastructure

**Comment by shirhatti** [comment]
Combining some identifiers (like pid and name in your example) make sense. However, combining anything with uid is probably erroneous since uid is guaranteed to be unique.

I'm not proposing we do anything about it and stick to your current proposal. It's just something I would watch for in future feedback

**Comment by kkeirstead** [comment]
> How would a user be able to identify the default process since we're now codifying that notion in configuration?

Looking at this and Wiktor's reply, should this be a separate GitHub issue? Based on my understanding of it, I think it should be addressed, but I'm not sure it's inherently attached to this issue (I could also be very wrong, given that my experience with the default process has been pretty limited). If you want, I can work on adding in that functionality before putting out a PR for this feature; otherwise, we can make a new issue for it and I could probably pick that up unless Justin has his eye on some other things for me.

**Comment by jander-msft** [comment]
> > How would a user be able to identify the default process since we're now codifying that notion in configuration?
> 
> 
> 
> Looking at this and Wiktor's reply, should this be a separate GitHub issue?

I think it is simple enough to refactor the `/processes/{id}` route to be `/process?pid={pid}&...` with support for the default process as part of this issue/pr. However, I'm fine with making it a separate issue/pr too.
