### ISSUE TITLE
Report Process.GetCurrentProcess().Threads.Count;

### ISSUE THREAD

**Issue by darraghjones** [dotnet/dotnet-monitor#842]
## Background and Motivation

I am interested in seeing the number of threads in a .net process.

## Proposed Feature

Currently all existing thread metrics appear to be threadpool related.

**Comment by jander-msft** [comment]
This would need to be added to the runtime before dotnet-monitor could consume it. Here's the corresponding issue in dotnet/runtime if you would like to add to it: https://github.com/dotnet/runtime/issues/47165

I'll be closing the issue here since we cannot take action until the EventCounter has been added to the runtime.
