### ISSUE TITLE
Runtime traces generationusing Dotnet Monitor

### ISSUE THREAD

**Issue by Saipavan018** [dotnet/dotnet-monitor#908]
Hi all,

       I installed dotnet monitor through your documentation and started dotnet monitor collect query to start the service .

Now I am running .net application from visual studio I am running this application but not generating traces,logs metrics for this application at runtime 

And I tried with the localhost:52323,localhost:5232/traces and also 52325  if I am trying using these ports than showing this localhost can't be host..

Can u help me on this .

**Comment by Saipavan018** [comment]
Hi @hoyosjs 
   Can u help me on this issue while running this application I am able to get the running application process I'd but I am not able get the traces metrics logs ...
If I am trying to /trace/pid or logs/pid I am getting this localhost page can't be found
In my console showing like this...
![IMG_20211001_213834__01](https://user-images.githubusercontent.com/87936491/135655228-a9fcdf17-8b2c-4aa7-ab43-9970bb5d465f.jpg)

**Comment by jander-msft** [comment]
Please don't at specific people. While hoyosjs is knowledgeable about dotnet-monitor, he might not know how to specifically help.

The error from your picture describes the problem: "System.InvalidOperationException: No default process configuration has been set". If you read the `/trace` route [documentation](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/api/trace-get.md#uri-parameters), it describes the behavior when you do not specify a process in the route; it falls back to the configured default process. Since the default process was not configured, it fails the HTTP request.

You either need to [configure the default process](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#default-process-configuration) or specify a process as part of the route e.g. `/trace?pid=12345`.

**Comment by Saipavan018** [comment]
@jander-msft  tq for your help working fyn now 
And but traces will be after stoping the running machine only able to stop or at runtime may I able to stop because after stopping the running application it will take 1-2 mins to complete the traces file download.

**Comment by jander-msft** [comment]
> @jander-msft  tq for your help working fyn now 
> 
> And but traces will be after stoping the running application only able to see the traces file or  may I able to stop the traces file because after stopping the running application it will take 1-2 mins to complete the traces file download.
> 
> 

I think what you are observing is the rundown information being sent at the end of the trace. This information is useful for symbolicating stack frames that are associated with individual events. If you don't need that information and only need the information found in the events themselves, then you can disable rundown in your traces. You'll need to use this HTTP route with the POST method to do that: documentation/api/trace-custom.md
